trigger:
  - main
  - master

parameters:
  - name: environment
    type: string
    default: 'dev'
    values:
      - dev
      - sit
      - uat
      - staging
      - prod

  - name: action
    type: string
    default: 'show-vms'
    values:
      - add
      - delete
      - destroy-infra
      - show-vms
      - cost
      - backend-setup
      - backend-delete

  - name: params
    type: string
    default: ''

jobs:
- job: RunAutomation
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - checkout: self

  - script: |
      echo "Running automation.sh with:"
      echo "  Environment: ${{ parameters.environment }}"
      echo "  Action: ${{ parameters.action }}"
      echo "  Params: ${{ parameters.params }}"
      
      # Split params into array if needed
      PARAM_ARRAY=()
      if [ -n "${{ parameters.params }}" ]; then
        # Convert space separated params string into array
        read -r -a PARAM_ARRAY <<< "${{ parameters.params }}"
      fi

      # Build command with params
      CMD="bash multi-env-vm-creation-updated/scripts/automation.sh ${{ parameters.environment }} ${{ parameters.action }} ${PARAM_ARRAY[@]}"
      echo "Executing: $CMD"
      eval $CMD
    displayName: Run Automation Script