trigger:
- main
- master

parameters:
  - name: action
    type: string
    default: 'backend-setup'
    values:
      - backend-setup
      - backend-delete

jobs:
- job: BackendSetupDelete
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - checkout: self

  - script: |
      echo "Running automation.sh with action: ${{ parameters.action }}"

      CMD="bash multi-env-vm-creation-updated/scripts/automation.sh dummy ${{ parameters.action }}"
      echo "Executing: $CMD"
      eval $CMD
    displayName: Run Backend Setup/Delete Script
