trigger: none

jobs:
- job: BackendSetupDelete
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - checkout: self

  - task: AzureCLI@2
    displayName: 'Run Backend Setup/Delete Script'
    inputs:
      azureSubscription: 'my-terraform-pipeline-sp'
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        echo "Running automation.sh with action: backend-${{ parameters.action }}"
        bash multi-env-vm-creation-updated/scripts/automation.sh dummy backend-${{ parameters.action }}
    env:
      AZURE_DEVOPS_EXT_AZURE_RM_SERVICE_PRINCIPAL_CERTIFICATE_PATH: $(AZURE_DEVOPS_EXT_AZURE_RM_SERVICE_PRINCIPAL_CERTIFICATE_PATH)

parameters:
- name: action
  type: string
  default: 'setup'
  values:
  - setup
  - delete
