parameters:
  - name: environment
    type: string
    default: 'dev'
    values:
      - dev
      - sit
      - uat
      - staging
      - prod

  - name: action
    type: string
    default: 'backend-setup'
    values:
      - backend-setup
      - backend-delete
      - add
      - delete
      - destroy-infra
      - show-vms
      - cost

  - name: params
    type: string
    default: ''
