trigger:
- master
- main

parameters:
  - name: environment
    type: string
    default: 'dev'
  - name: action
    type: string
    default: 'create'
  - name: count
    type: string
    default: '1'

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self

- script: |
    echo "Current directory: $(pwd)"
    echo "Listing files in root:"
    ls -la
    echo "Listing multi-env-vm-creation-updated/scripts directory:"
    ls -la multi-env-vm-creation-updated/scripts

    bash multi-env-vm-creation-updated/scripts/automation.sh '${{ parameters.environment }}' '${{ parameters.action }}' '${{ parameters.count }}'
  displayName: 'Run Automation Script'
